import Head from "next/head";
import Image from "next/image";
import hero from "../public/Hero.png";

export default function Home() {
  return (
    <div className="px-10 h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </div>
  );
}